# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(blank=True, default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='intro',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_title',
            field=models.CharField(blank=True, default='Untitled', max_length=200),
        ),
    ]
