# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0002_auto_20160419_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='total_day',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
