# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0003_plan_total_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
