# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('note_title', models.CharField(blank=True, max_length=200)),
                ('title_image', models.CharField(blank=True, default='https://yumengxemr.s3.amazonaws.com/id-None', max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('place', models.CharField(blank=True, max_length=256)),
                ('content', models.CharField(blank=True, max_length=512)),
                ('picture', models.CharField(blank=True, max_length=256)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notedetail', to='gotravel.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('place', models.CharField(max_length=256)),
                ('intro', models.CharField(blank=True, max_length=256)),
                ('creation_time', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plandetail', to='gotravel.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[(b'Male', b'Male'), (b'Female', b'Female')], default='M', max_length=10)),
                ('bio', models.CharField(blank=True, max_length=430)),
                ('image_url', models.CharField(blank=True, default='https://yumengxemr.s3.amazonaws.com/id-2', max_length=256)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
