# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planid', models.CharField(max_length=256)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=256)),
                ('intro', models.CharField(blank=True, max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=256)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('picture', models.CharField(blank=True, max_length=256)),
                ('video', models.CharField(blank=True, max_length=256)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[(b'M', b'Not relevant'), (b'F', b'Review')], default='M', max_length=10)),
                ('bio', models.CharField(blank=True, max_length=430)),
                ('image_url', models.CharField(blank=True, default='https://yumengxemr.s3.amazonaws.com/id-2', max_length=256)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantitle', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
