# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_title',
            field=models.CharField(max_length=200),
        ),
    ]
