# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='note',
            name='followers',
        ),
        migrations.AddField(
            model_name='note',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
