# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 28, 20, 54, 35, 271401, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
