# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 21:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gotravel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(blank=True, max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('title_image', models.CharField(blank=True, default='https://yumengxemr.s3.amazonaws.com/id-None', max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=256)),
                ('content', models.CharField(blank=True, max_length=512)),
                ('picture', models.CharField(blank=True, max_length=256)),
                ('video', models.CharField(blank=True, max_length=256)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotravel.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('state', models.CharField(max_length=256)),
                ('county', models.CharField(max_length=256)),
                ('intro', models.CharField(blank=True, max_length=256)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotravel.Plan')),
            ],
        ),
        migrations.RemoveField(
            model_name='newplan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='oldplan',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='owner',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'Male', b'Male'), (b'Female', b'Female')], default='M', max_length=10),
        ),
        migrations.DeleteModel(
            name='NewPlan',
        ),
        migrations.DeleteModel(
            name='OldPlan',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
