# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0002_auto_20160403_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
