# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotravel', '0003_auto_20160407_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
